# This file contains the configuration for various scripts used in PhantomBuster.
# Each script has a unique ID, a name, and a set of arguments that define its behavior.

- id: 3112
  name: LinkedIn Profile Visitor.js
  required:
    - spreadsheetUrl
  arguments:
    numberOfAddsPerLaunch: 10       # Number of profiles to visit per launch
    saveImg: True                   # Save profile images
    takeScreenshot: False           # Take a screenshot of the profile
    takePartialScreenshot: False    # Take a partial screenshot of the profile
    updateCrmContacts: False         # Update CRM contacts with profile data
    emailChooser: none              # Email discovery service by Phantombuster
    scrapeRecommendations: True     # Extract the profile’s recommendations - received/ given
    scrapeAccomplishments: True     # Extract the profile’s accomplishments - courses/ projects/ languages/ publications
    scrapeLicenses: True            # Extract the profile’s licenses and certifications
    scrapeInterests: True           # Extract the profile’s interests - companies/ groups/ schools
    onlyCurrentJson: True           # Only save the current JSON data, not the full history

- id: 9136
  name: LinkedIn Activity Extractor.js
  arguments:
    numberMaxOfPosts: 20            # Number of items to extract per activity type
    numberOfLinesPerLaunch: 10      # Number of profiles to process per launch
    csvName: result                 # Name of the CSV file to save results
    activitiesToScrape: [           # Types of activity to extract for profiles
      "Post",
      "Article",
      "Comment",
      "Reaction",
      "Document",
      "Newsletter",
      "Event"
    ]