# This file contains the configuration for various scripts used in PhantomBuster.
# Each script has a unique ID, a name, and a set of arguments that define its behavior.

- id: 3112
  name: LinkedIn Profile Visitor.js
  required:
    - spreadsheetUrl
  arguments:
    numberOfAddsPerLaunch: 10       # Number of profiles to visit per launch
    saveImg: True                   # Save profile images
    takeScreenshot: False           # Take a screenshot of the profile
    takePartialScreenshot: False    # Take a partial screenshot of the profile
    updateCrmContacts: False         # Update CRM contacts with profile data
    emailChooser: none              # Email discovery service by Phantombuster
    scrapeRecommendations: True     # Extract the profile’s recommendations - received/ given
    scrapeAccomplishments: True     # Extract the profile’s accomplishments - courses/ projects/ languages/ publications
    scrapeLicenses: True            # Extract the profile’s licenses and certifications
    scrapeInterests: True           # Extract the profile’s interests - companies/ groups/ schools
    onlyCurrentJson: True           # Only save the current JSON data, not the full history

- id: 9136
  name: LinkedIn Activity Extractor.js
  required:
    - spreadsheetUrl
  arguments:
    numberMaxOfPosts: 20            # Number of items to extract per activity type
    numberOfLinesPerLaunch: 10      # Number of profiles to process per launch
    csvName: result                 # Name of the CSV file to save results
    activitiesToScrape: [           # Types of activity to extract for profiles
      "Post",
      "Article",
      "Comment",
      "Reaction",
      "Document",
      "Newsletter",
      "Event"
    ]

- id: 4485
  name: Twitter Profile URL Finder.js
  required:
    - spreadsheetUrl
  arguments:
    market: es-ES                    # Choose which market to search for profiles in

- id: 9375
  name: Twitter Profile Scraper.js
  required:
    - spreadsheetUrl
  arguments:
    numberProfilesPerLaunch: 60 
    
- id: 30442
  name: Twitter Tweet Extractor.js
  required:
    - spreadsheetUrl
  arguments:
    feedType: tweets-replies         # Type of feed to extract tweets from
    numberOfTweetsPerProfile: 100    # Number of tweets to extract per profile (Verified acc up to 10.000 posts/day, Unverified up to 1000posts/day, new accounts up to 500posts/day)